<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Api2\Service\AsnService' shared autowired service.

include_once $this->targetDirs[3].'/src/Api2/Service/AsnService.php';

return $this->privates['App\Api2\Service\AsnService'] = new \App\Api2\Service\AsnService('127.0.0.1', 8086, 'asrank', 'asrankuser', 'rankas', 'autogen', ($this->privates['App\Api2\Helper\ReqUtils'] ?? $this->load('getReqUtilsService.php')), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
