<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Api2\Controller\AsnController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Api2/Controller/AsnController.php';

$this->services['App\Api2\Controller\AsnController'] = $instance = new \App\Api2\Controller\AsnController(500, 1, ($this->privates['App\Api2\Service\AsnService'] ?? $this->load('getAsnServiceService.php')), ($this->privates['App\Api2\Service\RelationService'] ?? $this->load('getRelationServiceService.php')), ($this->privates['App\Api2\Helper\ReqUtils'] ?? $this->load('getReqUtilsService.php')));

$instance->setContainer(($this->privates['.service_locator.ychIlgF'] ?? $this->load('get_ServiceLocator_YchIlgFService.php'))->withContext('App\\Api2\\Controller\\AsnController', $this));

return $instance;
