<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Api2\Controller\DatasetController' shared autowired service.

include_once $this->targetDirs[3].'/src/Api2/Service/DatasetService.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Api2/Controller/DatasetController.php';

$a = ($this->privates['App\Api2\Helper\ReqUtils'] ?? $this->load('getReqUtilsService.php'));

$this->services['App\Api2\Controller\DatasetController'] = $instance = new \App\Api2\Controller\DatasetController(500, 1, new \App\Api2\Service\DatasetService('127.0.0.1', 8086, 'asrank', 'asrankuser', 'rankas', 'autogen', $a, ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService())), $a);

$instance->setContainer(($this->privates['.service_locator.ychIlgF'] ?? $this->load('get_ServiceLocator_YchIlgFService.php'))->withContext('App\\Api2\\Controller\\DatasetController', $this));

return $instance;
