<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Rest\OrgRestController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/Rest/OrgRestController.php';

$this->services['App\Controller\Rest\OrgRestController'] = $instance = new \App\Controller\Rest\OrgRestController(($this->privates['App\Service\OrgService'] ?? $this->load('getOrgServiceService.php')), ($this->privates['App\Service\AsnService'] ?? $this->load('getAsnService2Service.php')), ($this->privates['App\Helper\ReqUtils'] ?? $this->load('getReqUtils2Service.php')));

$instance->setContainer(($this->privates['.service_locator.ychIlgF'] ?? $this->load('get_ServiceLocator_YchIlgFService.php'))->withContext('App\\Controller\\Rest\\OrgRestController', $this));

return $instance;
