<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Api2\Service\RelationService' shared autowired service.

include_once $this->targetDirs[3].'/src/Api2/Service/RelationService.php';

return $this->privates['App\Api2\Service\RelationService'] = new \App\Api2\Service\RelationService('127.0.0.1', 8086, 'asrank', 'asrankuser', 'rankas', 'autogen', ($this->privates['App\Api2\Helper\ReqUtils'] ?? $this->load('getReqUtilsService.php')), ($this->privates['App\Api2\Service\AsnService'] ?? $this->load('getAsnServiceService.php')), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
