<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Helper\ReqUtils' shared autowired service.

include_once $this->targetDirs[3].'/src/Helper/ReqUtils.php';

return $this->privates['App\Helper\ReqUtils'] = new \App\Helper\ReqUtils(500, 1, ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
